# Makefile created by mkmf $Id: mkmf,v 18.0.18.4

SRCROOT = /work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_parametric/IDEAL/exps/objs/



include /work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_home/templates/intel_default.mk


.DEFAULT:
	-echo $@ does not exist.
all: /work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_parametric/IDEAL/exps/1KM/EXEC/boundary_parametric.exe
SRC =
OBJ =
clean: neat
	-rm -f ./work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_parametric/IDEAL/exps/1KM/EXEC/boundary_parametric.exe.cppdefs $(OBJ) /work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_parametric/IDEAL/exps/1KM/EXEC/boundary_parametric.exe
neat:
	-rm -f $(TMPFILES)
TAGS: $(SRC)
	etags $(SRC)
tags: $(SRC)
	ctags $(SRC)
/work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_parametric/IDEAL/exps/1KM/EXEC/boundary_parametric.exe: $(OBJ) 
	$(LD) $(OBJ) -o /work2/noaa/nos-surge/mjisan/ufs-weather-model/HBL_V_DEV5/INIT/boundary_parametric/IDEAL/exps/1KM/EXEC/boundary_parametric.exe  $(LDFLAGS)
